// ─────────────────────────────────────────────────────────────────────────────
// MOCK DATA — Replace with real API calls in Phase 2
// ─────────────────────────────────────────────────────────────────────────────

export const PRIORITIES = [
  {
    id: 'p1',
    title: 'Review Series A pitch deck',
    subject: 'Pitch deck v2 — please review slides 8–12 before Thursday',
    timeAgo: '2h',
    initials: 'SC',
    project: 'Series A',
    priority: 'urgent',
    due: 'Today, 5:00 PM',
    assignedFrom: 'Sarah Chen',
    senderEmail: 'sarah.chen@company.com',
    action: 'Open deck and add comments to slides 8–12',
    aiSummary:
      'Sarah sent an updated version 2 hours ago. The deck has 18 slides — slides 8–12 cover financial projections that she flagged as needing your sign-off before the Sequoia call Thursday.',
    aiContext:
      'Sequoia meeting is Thursday at 11am. This is the second revision. Your main feedback last time was on the TAM slide and revenue model.',
    relatedPeople: ['Sarah Chen', 'James Okonkwo (CFO)'],
    suggestedReply:
      'Hey Sarah — will get you feedback on slides 8–12 by EOD today. Might have a question on the revenue assumptions, will flag in comments.',
  },
  {
    id: 'p2',
    title: 'Respond to Marcos on partnership terms',
    subject: 'Re: Term sheet revisions — IP clause in section 4 needs response',
    timeAgo: '1d',
    initials: 'MR',
    project: 'Partnerships',
    priority: 'high',
    due: 'Tomorrow, 12:00 PM',
    assignedFrom: 'Marcos Rivera',
    senderEmail: 'marcos.r@ventures.io',
    action: 'Draft response covering IP clauses in section 4',
    aiSummary:
      'Marcos sent term sheet revisions yesterday. The key sticking point is section 4 (IP ownership for co-developed integrations).',
    aiContext:
      "Previous thread shows you agreed in principle to shared IP but your lawyer flagged joint ownership complications. Lisa (Legal) suggested a licensing model instead.",
    relatedPeople: ['Marcos Rivera', 'Lisa Tran (Legal)'],
    suggestedReply:
      "Marcos — looping in Lisa to finalize the IP language in section 4. We're aligned on the licensing approach.",
  },
  {
    id: 'p3',
    title: 'Approve Q3 budget proposal',
    subject: 'Q3 Budget Proposal ($2.4M) — awaiting your approval',
    timeAgo: '3h',
    initials: 'DP',
    project: 'Operations',
    priority: 'high',
    due: 'Today, 3:00 PM',
    assignedFrom: 'David Park',
    senderEmail: 'david.park@internal.co',
    action: 'Review budget doc and approve or leave blocking comments',
    aiSummary:
      "David submitted the Q3 budget this morning. Total ask is $2.4M — up 18% from Q2.",
    aiContext:
      'Your Q2 actuals came in 6% under budget. The board expects a lean Q3 given macro conditions.',
    relatedPeople: ['David Park (Finance)', 'Board (audit copy)'],
    suggestedReply:
      "David — approving the base Q3 budget. Holding off on the stretch scenario for now.",
  },
  {
    id: 'p4',
    title: 'Finalize VP Sales hiring rubric',
    subject: 'VP Sales rubric — section 3 still empty, interviews start Monday',
    timeAgo: '5h',
    initials: 'AT',
    project: 'Hiring',
    priority: 'medium',
    due: 'Friday',
    assignedFrom: 'Amanda Torres',
    senderEmail: 'amanda.t@internal.co',
    action: 'Complete scorecard criteria section before first interviews',
    aiSummary:
      'Amanda shared a draft rubric for VP Sales. Cultural-fit and leadership sections are complete. Section 3 (sales competencies) is blank.',
    aiContext:
      'You mentioned wanting someone who has sold $1M+ deals and managed a 10+ person team.',
    relatedPeople: ['Amanda Torres (HR)', 'Priya Mehta (Panel lead)'],
    suggestedReply:
      "Amanda — I'll fill in section 3 by Thursday EOD. Key criteria: $1M+ ACV experience, managed 10+ AEs.",
  },
];

export const WAITING = [
  { id: 'w1', person: 'Sarah Chen',    initials: 'SC', role: 'Head of Design', waiting: '2 days',  project: 'Series A',    action: 'Review pitch deck slides 8–12',      urgent: true  },
  { id: 'w2', person: 'Marcos Rivera', initials: 'MR', role: 'Partner, BD',   waiting: '1 day',   project: 'Partnerships', action: 'Respond to IP clause in section 4', urgent: true  },
  { id: 'w3', person: 'David Park',    initials: 'DP', role: 'Finance Lead',   waiting: '3 hours', project: 'Operations',   action: 'Approve Q3 budget document',        urgent: false },
  { id: 'w4', person: 'Amanda Torres', initials: 'AT', role: 'People Ops',     waiting: '5 hours', project: 'Hiring',       action: 'Complete VP Sales rubric section 3', urgent: false },
];

export const METRICS = [
  { value: '7', label: 'Action Items',   sub: '3 urgent'   },
  { value: '4', label: 'Waiting On',     sub: '2 over 24h' },
  { value: '2', label: 'Due Today',      sub: 'by 5:00 PM' },
];

export const TASKS = [
  {
    id: 't1',
    title: 'Review Series A pitch deck',
    subject: 'Pitch deck v2 — please review slides 8–12 before Thursday',
    timeAgo: '2h',
    initials: 'SC',
    project: 'Series A',
    priority: 'urgent',
    due: 'Today, 5:00 PM',
    assignedFrom: 'Sarah Chen',
    senderEmail: 'sarah.chen@company.com',
    status: 'open',
    action: 'Open deck and add comments to slides 8–12',
    aiSummary: 'Sarah sent an updated version 2 hours ago. The deck has 18 slides — slides 8–12 cover financial projections that she flagged as needing your sign-off before the Sequoia call Thursday.',
    aiContext: 'Sequoia meeting is Thursday at 11am. This is the second revision. Your main feedback last time was on the TAM slide and revenue model.',
    relatedPeople: ['Sarah Chen', 'James Okonkwo (CFO)'],
    suggestedReply: 'Hey Sarah — will get you feedback on slides 8–12 by EOD today. Might have a question on the revenue assumptions, will flag in comments.',
  },
  {
    id: 't2',
    title: 'Respond to Marcos on partnership terms',
    subject: 'Re: Term sheet revisions — IP clause in section 4 needs response',
    timeAgo: '1d',
    initials: 'MR',
    project: 'Partnerships',
    priority: 'urgent',
    due: 'Today, 12:00 PM',
    assignedFrom: 'Marcos Rivera',
    senderEmail: 'marcos.r@ventures.io',
    status: 'open',
    action: 'Draft response covering IP clauses in section 4',
    aiSummary: 'Marcos sent term sheet revisions yesterday. The key sticking point is section 4 (IP ownership for co-developed integrations).',
    aiContext: 'Previous thread shows you agreed in principle to shared IP but your lawyer flagged joint ownership complications.',
    relatedPeople: ['Marcos Rivera', 'Lisa Tran (Legal)'],
    suggestedReply: `Marcos — looping in Lisa to finalize the IP language in section 4. We're aligned on the licensing approach.`,
  },
  {
    id: 't3',
    title: 'Approve Q3 budget proposal',
    subject: 'Q3 Budget Proposal ($2.4M) — awaiting your approval',
    timeAgo: '3h',
    initials: 'DP',
    project: 'Operations',
    priority: 'high',
    due: 'Today, 3:00 PM',
    assignedFrom: 'David Park',
    senderEmail: 'david.park@internal.co',
    status: 'open',
    action: 'Review budget doc and approve or leave blocking comments',
    aiSummary: 'David submitted the Q3 budget this morning. Total ask is $2.4M — up 18% from Q2.',
    aiContext: 'Your Q2 actuals came in 6% under budget. The board expects a lean Q3 given macro conditions.',
    relatedPeople: ['David Park (Finance)', 'Board (audit copy)'],
    suggestedReply: 'David — approving the base Q3 budget. Holding off on the stretch scenario for now.',
  },
  {
    id: 't4',
    title: 'Finalize VP Sales hiring rubric',
    subject: 'VP Sales rubric — section 3 still empty, interviews start Monday',
    timeAgo: '5h',
    initials: 'AT',
    project: 'Hiring',
    priority: 'high',
    due: 'Friday',
    assignedFrom: 'Amanda Torres',
    senderEmail: 'amanda.t@internal.co',
    status: 'open',
    action: 'Complete scorecard criteria section before first interviews',
    aiSummary: 'Amanda shared a draft rubric for VP Sales. Cultural-fit and leadership sections are complete. Section 3 (sales competencies) is blank.',
    aiContext: 'You mentioned wanting someone who has sold $1M+ deals and managed a 10+ person team.',
    relatedPeople: ['Amanda Torres (HR)', 'Priya Mehta (Panel lead)'],
    suggestedReply: `Amanda — I'll fill in section 3 by Thursday EOD. Key criteria: $1M+ ACV experience, managed 10+ AEs.`,
  },
  {
    id: 't5',
    title: 'Sign off on product roadmap Q3',
    subject: 'Product roadmap Q3 — needs exec sign-off before all-hands',
    timeAgo: '1d',
    initials: 'PK',
    project: 'Product',
    priority: 'high',
    due: 'Tomorrow',
    assignedFrom: 'Priya Kumar',
    senderEmail: 'priya.kumar@internal.co',
    status: 'open',
    action: 'Review roadmap doc and leave approval comment',
    aiSummary: `Priya needs exec sign-off on the Q3 product roadmap before Thursday's all-hands presentation.`,
    aiContext: 'The roadmap includes 3 major feature launches: AI briefing, smart snooze, and people graph.',
    relatedPeople: ['Priya Kumar (PM)', 'Eng leads'],
    suggestedReply: `Priya — roadmap looks solid. Approved. One note: let's add a timeline buffer for the people graph feature.`,
  },
  {
    id: 't6',
    title: 'Follow up with Christine on access',
    subject: 'APIsec University access — Christine still waiting',
    timeAgo: '2d',
    initials: 'CB',
    project: 'Operations',
    priority: 'medium',
    due: 'This week',
    assignedFrom: 'Christine Bevilacqua',
    senderEmail: 'c.bevilacqua@apisec.ai',
    status: 'open',
    action: 'Reply to Christine with access credentials or ETA',
    aiSummary: 'Christine has been waiting 2 days for APIsec University platform access. No reply sent yet.',
    aiContext: 'Original request came in via email. She mentioned needing it for a training session this week.',
    relatedPeople: ['Christine Bevilacqua'],
    suggestedReply: 'Hi Christine — apologies for the delay. Access should be live now. Let me know if you hit any issues.',
  },
  {
    id: 't7',
    title: `Confirm Veera's sync agenda`,
    subject: 'Daily Sync — confirm agenda items for tomorrow',
    timeAgo: '5d',
    initials: 'VC',
    project: 'Partnerships',
    priority: 'medium',
    due: 'Tomorrow',
    assignedFrom: 'Veera Chembrolu',
    senderEmail: 'veera.c@company.com',
    status: 'snoozed',
    action: 'Reply with 3 agenda items for daily sync',
    aiSummary: `Veera needs confirmation on agenda items for tomorrow's daily sync with the partnerships team.`,
    aiContext: 'Last sync covered the Marcos deal and two new inbound partnership inquiries.',
    relatedPeople: ['Veera Chembrolu'],
    suggestedReply: 'Veera — agenda for tomorrow: 1) Marcos term sheet update, 2) New partnership inbounds, 3) Q3 BD targets.',
  },
  {
    id: 't8',
    title: 'Review internship skills activity',
    subject: 'Internship & Applied Skills Activity 2026 — review attached brief',
    timeAgo: '5d',
    initials: 'AK',
    project: 'Hiring',
    priority: 'medium',
    due: 'Next week',
    assignedFrom: 'animesh_kumar',
    senderEmail: 'animesh.kumar@university.edu',
    status: 'open',
    action: 'Review internship brief and provide feedback',
    aiSummary: 'Animesh sent the internship skills activity brief for the 2026 cohort. Needs your review and feedback.',
    aiContext: `Last year's cohort had 12 interns. This year's brief proposes expanding to 20.`,
    relatedPeople: ['animesh_kumar', 'Amanda Torres (HR)'],
    suggestedReply: 'Thanks Animesh — will review by end of next week and share feedback. Expanding to 20 sounds promising.',
  },
  {
    id: 't9',
    title: 'Reply to Dan on APIsec progress',
    subject: `How's APIsec U going? — checking in from Dan`,
    timeAgo: '10d',
    initials: 'DB',
    project: 'Operations',
    priority: 'medium',
    due: 'This week',
    assignedFrom: 'Dan Barahona',
    senderEmail: 'dan.b@apisec.ai',
    status: 'open',
    action: 'Send Dan a brief progress update on APIsec University adoption',
    aiSummary: 'Dan from APIsec University is checking in on platform adoption after 10 days of access.',
    aiContext: 'Christine recently got access. Adoption metrics not yet tracked internally.',
    relatedPeople: ['Dan Barahona'],
    suggestedReply: `Hi Dan — good timing. Just got Christine onboarded. Early feedback is positive, will share metrics next week.`,
  },
];

// ─────────────────────────────────────────────────────────────────────────────
// PEOPLE — Contacts extracted from email threads
// ─────────────────────────────────────────────────────────────────────────────

export const PEOPLE = [
  {
    id: 'pe1',
    name: '"Bh - Seethanagaram [Union Bank Of India]"',
    initials: 'BS',
    email: 'ubin0827991@unionbankofindia.bank.in',
    org: 'Union Bank Of India',
    snippet: `Contact resolved from email communications. Name: "Bh - Seethanagaram [Union Bank Of India]".`,
  },
  {
    id: 'pe2',
    name: '"Dan Barahona, APIsec University"',
    initials: 'DB',
    email: 'apisec@y.kajabimail.net',
    org: 'APIsec University',
    snippet: `Contact resolved from email communications. Name: "Dan Barahona, APIsec University".`,
  },
  {
    id: 'pe3',
    name: 'animesh_kumar',
    initials: 'AK',
    email: 'animesh_kumar@elytespark.org',
    org: 'Elytespark',
    snippet: `Contact resolved from email communications. Name: animesh_kumar.`,
  },
  {
    id: 'pe4',
    name: 'Christine Bevilacqua',
    initials: 'CB',
    email: 'christine@apisec.ai',
    org: 'APIsec',
    snippet: `Contact resolved from email communications. Name: Christine Bevilacqua.`,
  },
  {
    id: 'pe5',
    name: 'MAHANKALI SAI RITHWIK',
    initials: 'MS',
    email: 'rikkumahan20@gmail.com',
    org: 'VIT Vellore',
    snippet: `Name of the student, Registration No 24BCE0682.`,
  },
  {
    id: 'pe6',
    name: 'Outskill',
    initials: 'OS',
    email: 'outskill@user.luma-mail.com',
    org: 'Outskill',
    snippet: `Contact resolved from email communications. Name: Outskill.`,
  },
  {
    id: 'pe7',
    name: 'Rithvik Mahankali',
    initials: 'RM',
    email: 'rikkumahan20@gmail.com',
    org: 'Personal',
    snippet: `Contact resolved from email communications. Name: Rithvik Mahankali.`,
  },
  {
    id: 'pe8',
    name: 'Veera Chembrolu',
    initials: 'VC',
    email: 'veera.c@mechispike.com',
    org: 'Mechispike',
    snippet: `Contact resolved from email communications. Name: Veera Chembrolu.`,
  },
  {
    id: 'pe9',
    name: 'Sarah Chen',
    initials: 'SC',
    email: 'sarah.chen@company.com',
    org: 'Company',
    snippet: `Head of Design. Sent pitch deck v2 for Series A review. Awaiting sign-off on slides 8–12.`,
  },
  {
    id: 'pe10',
    name: 'Marcos Rivera',
    initials: 'MR',
    email: 'marcos.r@ventures.io',
    org: 'Ventures IO',
    snippet: `Partner, BD. Sent term sheet revisions with IP clause sticking point in section 4.`,
  },
  {
    id: 'pe11',
    name: 'David Park',
    initials: 'DP',
    email: 'david.park@internal.co',
    org: 'Internal',
    snippet: `Finance Lead. Submitted Q3 budget proposal of $2.4M for approval.`,
  },
  {
    id: 'pe12',
    name: 'Amanda Torres',
    initials: 'AT',
    email: 'amanda.t@internal.co',
    org: 'Internal',
    snippet: `People Ops. Shared VP Sales hiring rubric — section 3 needs completion before Monday interviews.`,
  },
];
