-- ============================================================
-- Migration: 011_add_graphrag_tables
-- Description: Adds property graph tables, community clustering
--              tables, and semantic search RPC functions for the
--              Context-Aware Corporate Email GraphRAG pipeline.
-- ============================================================

-- Enable pgvector extension (idempotent)
CREATE EXTENSION IF NOT EXISTS vector;

-- ─────────────────────────────────────────────
-- 1. CONTACTS
-- Represents individuals (senders, recipients, people mentioned)
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS contacts (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  email         text        UNIQUE NOT NULL,
  name          text,
  organization  text,
  bio_summary   text,
  embedding     vector(1536),
  created_at    timestamptz DEFAULT now()
);

-- ─────────────────────────────────────────────
-- 2. PROJECTS
-- Represents focus areas / business initiatives
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS projects (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text        UNIQUE NOT NULL,
  description text,
  status      text        DEFAULT 'active',
  created_at  timestamptz DEFAULT now()
);

-- ─────────────────────────────────────────────
-- 3. THREADS
-- Groups related email messages under one Gmail thread
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS threads (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  gmail_thread_id text        UNIQUE NOT NULL,
  subject         text,
  semantic_summary text,
  project_id      uuid        REFERENCES projects(id) ON DELETE SET NULL,
  created_at      timestamptz DEFAULT now()
);

-- ─────────────────────────────────────────────
-- 4. EMAILS
-- Individual email messages (children of threads)
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS emails (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  message_id  text        UNIQUE NOT NULL,
  thread_id   uuid        REFERENCES threads(id)   ON DELETE CASCADE,
  sender_id   uuid        REFERENCES contacts(id)  ON DELETE RESTRICT,
  subject     text,
  body        text,
  snippet     text,
  received_at timestamptz NOT NULL,
  embedding   vector(1536),
  created_at  timestamptz DEFAULT now()
);

-- ─────────────────────────────────────────────
-- 5. COMMUNITY REPORTS
-- Louvain cluster summaries generated by the LLM
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS community_reports (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  title               text        NOT NULL,
  summary             text        NOT NULL,
  rating              numeric     NOT NULL,
  rating_explanation  text        NOT NULL,
  findings            jsonb       NOT NULL DEFAULT '[]'::jsonb,
  embedding           vector(1536),
  created_at          timestamptz DEFAULT now()
);

-- ─────────────────────────────────────────────
-- 6. COMMUNITY MEMBERS
-- Maps graph nodes (entities) to their community cluster
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS community_members (
  id            uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
  community_id  uuid  REFERENCES community_reports(id) ON DELETE CASCADE,
  node_id       uuid  NOT NULL,
  node_type     text  NOT NULL   -- 'contact' | 'project' | 'thread' | 'task'
);

-- ─────────────────────────────────────────────
-- 7. GRAPH EDGES
-- Property graph connections between entity nodes
-- ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS graph_edges (
  id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  source_id         uuid        NOT NULL,
  target_id         uuid        NOT NULL,
  source_type       text        NOT NULL,  -- 'contact' | 'project' | 'thread' | 'task'
  target_type       text        NOT NULL,
  relationship_type text        NOT NULL,  -- 'SENT_BY' | 'ASSIGNED_TO' | 'PART_OF' etc.
  description       text        NOT NULL,
  created_at        timestamptz DEFAULT now()
);

-- ─────────────────────────────────────────────
-- 8. EXTEND EXISTING TASKS TABLE
-- Add graph foreign keys (idempotent)
-- ─────────────────────────────────────────────
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS project_id  uuid REFERENCES projects(id)  ON DELETE SET NULL;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS assignee_id uuid REFERENCES contacts(id)  ON DELETE SET NULL;

-- ─────────────────────────────────────────────
-- 9. HNSW VECTOR INDEXES (cosine similarity)
-- Required for match_* RPC functions below
-- ─────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS contacts_embedding_idx
  ON contacts USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS emails_embedding_idx
  ON emails USING hnsw (embedding vector_cosine_ops);

CREATE INDEX IF NOT EXISTS community_reports_embedding_idx
  ON community_reports USING hnsw (embedding vector_cosine_ops);

-- ─────────────────────────────────────────────
-- 10. SUPPLEMENTARY BTREE INDEXES
-- ─────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS graph_edges_source_idx ON graph_edges (source_id);
CREATE INDEX IF NOT EXISTS graph_edges_target_idx ON graph_edges (target_id);
CREATE INDEX IF NOT EXISTS community_members_community_idx ON community_members (community_id);
CREATE INDEX IF NOT EXISTS community_members_node_idx ON community_members (node_id);

-- ─────────────────────────────────────────────
-- 11. RPC: match_contacts
-- Semantic nearest-neighbour search on contacts.embedding.
-- Used by GraphRAGStore.resolveContact() for entity resolution.
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION match_contacts(
  query_embedding  vector(1536),
  match_threshold  float    DEFAULT 0.85,
  match_count      int      DEFAULT 5
)
RETURNS TABLE (
  id            uuid,
  email         text,
  name          text,
  organization  text,
  bio_summary   text,
  similarity    float
)
LANGUAGE plpgsql STABLE SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    c.id,
    c.email,
    c.name,
    c.organization,
    c.bio_summary,
    1 - (c.embedding <=> query_embedding) AS similarity
  FROM contacts c
  WHERE c.embedding IS NOT NULL
    AND 1 - (c.embedding <=> query_embedding) >= match_threshold
  ORDER BY c.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- ─────────────────────────────────────────────
-- 12. RPC: match_emails
-- Semantic nearest-neighbour search on emails.embedding.
-- Used by GraphRAGQueryEngine local 2-hop search.
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION match_emails(
  query_embedding  vector(1536),
  match_threshold  float   DEFAULT 0.2,
  match_count      int     DEFAULT 5
)
RETURNS TABLE (
  id          uuid,
  message_id  text,
  thread_id   uuid,
  sender_id   uuid,
  subject     text,
  body        text,
  snippet     text,
  received_at timestamptz,
  similarity  float
)
LANGUAGE plpgsql STABLE SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    e.id,
    e.message_id,
    e.thread_id,
    e.sender_id,
    e.subject,
    e.body,
    e.snippet,
    e.received_at,
    1 - (e.embedding <=> query_embedding) AS similarity
  FROM emails e
  WHERE e.embedding IS NOT NULL
    AND 1 - (e.embedding <=> query_embedding) >= match_threshold
  ORDER BY e.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- ─────────────────────────────────────────────
-- 13. RPC: match_community_reports
-- Semantic nearest-neighbour search on community_reports.embedding.
-- Used by GraphRAGQueryEngine global map-reduce search.
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION match_community_reports(
  query_embedding  vector(1536),
  match_threshold  float   DEFAULT 0.2,
  match_count      int     DEFAULT 8
)
RETURNS TABLE (
  id                  uuid,
  title               text,
  summary             text,
  rating              numeric,
  rating_explanation  text,
  findings            jsonb,
  similarity          float
)
LANGUAGE plpgsql STABLE SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    cr.id,
    cr.title,
    cr.summary,
    cr.rating,
    cr.rating_explanation,
    cr.findings,
    1 - (cr.embedding <=> query_embedding) AS similarity
  FROM community_reports cr
  WHERE cr.embedding IS NOT NULL
    AND 1 - (cr.embedding <=> query_embedding) >= match_threshold
  ORDER BY cr.embedding <=> query_embedding
  LIMIT match_count;
END;
$$;

-- ─────────────────────────────────────────────
-- 14. RPC: get_entity_neighborhood
-- Returns 1-hop neighbors of a given node.
-- Exposed as an LLM tool for context-aware action-insight tracking.
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION get_entity_neighborhood(
  seed_node_id    uuid,
  max_hops        int  DEFAULT 1,
  max_neighbors   int  DEFAULT 20
)
RETURNS TABLE (
  node_id           uuid,
  node_type         text,
  relationship_type text,
  direction         text,   -- 'outbound' | 'inbound'
  description       text
)
LANGUAGE plpgsql STABLE SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  -- Outbound edges
  SELECT
    ge.target_id        AS node_id,
    ge.target_type      AS node_type,
    ge.relationship_type,
    'outbound'::text    AS direction,
    ge.description
  FROM graph_edges ge
  WHERE ge.source_id = seed_node_id
  UNION ALL
  -- Inbound edges
  SELECT
    ge.source_id        AS node_id,
    ge.source_type      AS node_type,
    ge.relationship_type,
    'inbound'::text     AS direction,
    ge.description
  FROM graph_edges ge
  WHERE ge.target_id = seed_node_id
  LIMIT max_neighbors;
END;
$$;

-- ─────────────────────────────────────────────
-- 15. RPC: find_path_between_entities
-- BFS-style 2-hop path finder between two entity nodes.
-- Exposed as an LLM tool for relational reasoning.
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION find_path_between_entities(
  source_node_id  uuid,
  target_node_id  uuid
)
RETURNS TABLE (
  hop             int,
  node_id         uuid,
  node_type       text,
  relationship_type text,
  description     text
)
LANGUAGE plpgsql STABLE SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  WITH RECURSIVE path_cte AS (
    -- Seed: direct connections from source
    SELECT
      1                     AS hop,
      ge.target_id          AS node_id,
      ge.target_type        AS node_type,
      ge.relationship_type,
      ge.description,
      ARRAY[source_node_id, ge.target_id] AS visited
    FROM graph_edges ge
    WHERE ge.source_id = source_node_id

    UNION ALL

    -- Expand one more hop
    SELECT
      p.hop + 1,
      ge.target_id,
      ge.target_type,
      ge.relationship_type,
      ge.description,
      p.visited || ge.target_id
    FROM path_cte p
    JOIN graph_edges ge ON ge.source_id = p.node_id
    WHERE p.hop < 2
      AND NOT (ge.target_id = ANY(p.visited))  -- no cycles
  )
  SELECT hop, node_id, node_type, relationship_type, description
  FROM path_cte
  WHERE node_id = target_node_id
  ORDER BY hop
  LIMIT 10;
END;
$$;

-- ─────────────────────────────────────────────
-- 16. RPC: get_entity_timeline
-- Returns all edges for a node ordered by creation date.
-- Exposed as an LLM tool for timeline/history queries.
-- ─────────────────────────────────────────────
CREATE OR REPLACE FUNCTION get_entity_timeline(
  entity_id   uuid,
  limit_rows  int  DEFAULT 20
)
RETURNS TABLE (
  edge_id           uuid,
  relationship_type text,
  direction         text,
  counterpart_id    uuid,
  counterpart_type  text,
  description       text,
  created_at        timestamptz
)
LANGUAGE plpgsql STABLE SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    ge.id               AS edge_id,
    ge.relationship_type,
    CASE WHEN ge.source_id = entity_id THEN 'outbound' ELSE 'inbound' END AS direction,
    CASE WHEN ge.source_id = entity_id THEN ge.target_id ELSE ge.source_id END AS counterpart_id,
    CASE WHEN ge.source_id = entity_id THEN ge.target_type ELSE ge.source_type END AS counterpart_type,
    ge.description,
    ge.created_at
  FROM graph_edges ge
  WHERE ge.source_id = entity_id OR ge.target_id = entity_id
  ORDER BY ge.created_at DESC
  LIMIT limit_rows;
END;
$$;
